
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwtevsnsivmpmikhtdmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3dGV2c25zaXZtcG1pa2h0ZG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzU1OTYsImV4cCI6MjA2MTUxMTU5Nn0.k1ftSd4K8P25NtxpfQ91GsM7P4uXa0lKP7D1FHIqxJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
);

// Función auxiliar para comprobar si un usuario es administrador
export async function isAdmin(): Promise<boolean> {
  const { data } = await supabase.auth.getUser();
  if (!data.user) return false;

  // Llamar a la función RPC en Supabase
  const { data: isAdminData, error } = await supabase
    .rpc('is_admin', { user_id: data.user.id });

  if (error) {
    console.error('Error checking admin status:', error);
    return false;
  }

  return isAdminData || false;
}
